### ISSUE TITLE
Search sequence in dictionnary not working with long sequences

### ISSUE THREAD

**Issue by gabrielctn** [gabrielctn/fasta_project#1]
`int searchSeqDictionary(Nucleic_Dict *nd, char *sequence) {
    if (nd == NULL) {
        return 0;
    }
    if (sequence[0] == '\0') {
        return nd->end;
    }
    return searchSeqDictionary(nd->child[dicoNucleicIndex(sequence[0])], sequence + 1);
}`

**Comment by mankalas** [comment]
"Not working", c'est ce que dit Mme Michu dans elle appelle le help desk... Quelle est l'erreur? Le comportement attendu? Les données qui posent problème?

**Comment by gabrielctn** [comment]
Quand on lance l'option 5 du menu (Recherche de séquence dans le dictionnaire), on copie colle une séquence nucléotidique du fichier S_pombe.fasta et il doit retourner un "Trouvé ! La séquence se trouve dans le dictionnaire". Or, si on essaye avec des très longues séquences (genre dans les 6000 par exemple) il retourne "Désolé, aucune séquence correspondante ne se trouve dans le dictionnaire" alors qu'elle devrait y être.

**Comment by mankalas** [comment]
Impeccable ce rapport d'erreur.

Hmm... A vue de nez, la taille n'est pas l'élément principal. 6000 ce n'est
pas suffisamment gros pour être problématique (6millions à la rigueur, ou
un multiple de 2 peut mettre la puce à l'oreille)
Souvent, plus la taille de données est importante, plus des cas
particuliers ont la probabilité d'apparaître (tu connais l'histoire des
singes qui écrivent Shakespeare ?). Ta chaîne de 6000, je la soupçonne
d'héberger des cas que vous n'avez pas prévus (doublons dans le
dictionnaire, séquences considérées impossible... J'en sais trop rien).
Comme je suppose que lire manuellement (oculairement devrais-je dire) est
impossible, la meilleure stratégie (comme souvent d'ailleurs) est la
dichotomie : testez la première moitié de la chaîne incriminée, et si
l'erreur n'apparaît pas, testez la deuxième. Puis testez la moitié de la
moitié qui fait défaut, etc.
Good luck!

**Comment by gabrielctn** [comment]
On a identifié l'origine du problème y'a genre 15 min en fait, c'est quand on fait le scanf pour récupérer la chaîne, quand on mesure la longueur de la chaîne qu'on rentre avant et après il y a une différence. Par exemple la 1ère séquence fait 5662 et le scanf en prend 4095 seulement. Et en essayant avec d'autres séquences plus longues on tombe à chaque fois sur 4095

**Comment by gabrielctn** [comment]
Il semble que ça soit une limitation du terminal: 
http://stackoverflow.com/questions/39546500/how-to-make-scanf-to-read-more-than-4095-characters-given-as-input

**Comment by mankalas** [comment]
4095 c'est 2^12-1. C'est pas souvent qu'on le rencontre celui là...

**Comment by gabrielctn** [comment]
Question, dans le code je fais plutôt un:
`system("stty -icanon");`
ou je rajoute la fonction `int clear_icanon(void)` de la solution de StackOverflow?

**Comment by gabrielctn** [comment]
Bon, les 2 marchent, et comme moins de code c'est du meilleur code, va pour le system().

**Comment by mankalas** [comment]
Un appel à `system`, c'est "sale". Tu changes l'état de l'environnement qui exécute ton programme, tu ne sais pas forcément les conséquences, il faut s'assurer que la commande ne retourne pas de code d'erreur, et s'il y en a un, il faut récupérer le message sur la sortie standard... C'est tentant de déléguer des trucs à `system`, mais un programme qui se suffit à lui-même est de bien meilleure qualité qu'un programme qui intéragit avec l'extérieur (je parle bien d'aller *modifier* l'extérieur, pas d'utiliser des bibliothèques hein).

Je pense qu'au contraire, copier la fonction C est une meilleure solution parce que :
- tu maîtrises 100% de ce qu'il se passe à l'exécution de ton code ;
- tu gères les erreurs au moment où elles arrivent ;
- tu ne dépends pas du monde extérieur ;
- ça va plus vite (ça ne va pas faire ramer ton programme, mais encore une fois, les bonnes habitudes, il faut les prendre tôt... tout en sachant que l'optimisation prématurée est le pire des maux... Tout est une question d'équilibre hein? En gros, si tu prends des bonnes habitudes d'optimisation, cela te coûtera moins cher d'optimiser à l'avenir puisque ce sera un automatisme... Mais 'faut pas devenir nazi non plus)

**Comment by gabrielctn** [comment]
Okay ça marche, merci Vincent :)

**Comment by mankalas** [comment]
Mais de rien.
Le fait de modifier l'extérieur le moins possible, et de s'exposer au monde extérieur le moins possible est quelque chose de super important. Lorsque vous ferez de l'orienté objet, ce sera vital pour écrire des programmes robustes et de bonnes qualité.
